export  const MOVIE_LIST_REQUEST = "MOVIE_LIST_REQUEST";
export  const MOVIE_LIST_SUCCESS = "MOVIE_LIST_SUCCESS";
export  const MOVIE_LIST_FAIL = "MOVIE_LIST_FAIL";


export const ADD_WATCHED_MOVIE_REQUEST = "ADD_WATCHED_MOVIE_REQUEST";
export const ADD_WATCHED_MOVIE_SUCCESS = "ADD_WATCHED_MOVIE_SUCCESS";
export const ADD_WATCHED_MOVIE_FAIL = "ADD_WATCHED_MOVIE_FAIL";
// export const ADD_MOVIE_RESET = "ADD_MOVIE_RESET";


export const SEARCH_MOVIE_REQUEST = "SEARCH_MOVIE_REQUEST";
export const SEARCH_MOVIE_SUCCESS = "SEARCH_MOVIE_SUCCESS";
export const SEARCH_MOVIE_FAIL = "SEARCH_MOVIE_FAIL";



export const WATCHED_MOVIE_REQUEST = "WATCHED_MOVIE_REQUEST";
export const WATCHED_MOVIE_SUCCESS = "WATCHED_MOVIE_SUCCESS";
export const WATCHED_MOVIE_FAIL = "WATCHED_MOVIE_FAIL";